org.gradle.parallel=false
org.gradle.java.home=E:/JDK25
loom.mixin.useLegacyMixinAp = true

# Mod Properties
mod_name=Max Elytra Fly Speed
mod_version=1.0.20+26.3
maven_group=net.instantgratification
archives_base_name=max-elytra-fly-speed

# Dependencies
minecraft_version=26.3-snapshot-6
fabric_loader_version=0.19.3
fabric_version=0.156.1+26.3

# Loom
fabric.loom.suppressJavaCompatibilityChecks=true
loom.suppressJavaCompatibilityChecks=true

# DasikLibrary
dasik_library_version=1.8.24
